The Haiku Book: BAffineTransform Class Reference
API Documentation
BAffineTransform Class Reference
Interface Kit | (libbe.so)
Undocumented class.
Inherits BFlattenable.
Public Member Functions
BAffineTransform ()
Undocumented public method.
BAffineTransform (const BAffineTransform &copyFrom)
Undocumented public method.
BAffineTransform (double sx, double shy, double shx, double sy, double tx, double ty)
Undocumented public method.
virtual ~BAffineTransform ()
Undocumented public method.
void Apply (BPoint *point) const
Undocumented public method.
void Apply (BPoint *points, uint32 count) const
Undocumented public method.
BPoint Apply (const BPoint &point) const
Undocumented public method.
void Apply (double *x, double *y) const
Undocumented public method.
void ApplyInverse (BPoint *point) const
Undocumented public method.
void ApplyInverse (BPoint *points, uint32 count) const
Undocumented public method.
BPoint ApplyInverse (const BPoint &point) const
Undocumented public method.
void ApplyInverse (double *x, double *y) const
Undocumented public method.
double Determinant () const
Undocumented public method.
virtual status_t Flatten (void *buffer, ssize_t size) const
Undocumented public method.
virtual ssize_t FlattenedSize () const
Undocumented public method.
const BAffineTransform & FlipX ()
Undocumented public method.
const BAffineTransform & FlipY ()
Undocumented public method.
bool GetAffineParameters (double *translationX, double *translationY, double *rotation, double *scaleX, double *scaleY, double *shearX, double *shearY) const
Undocumented public method.
void GetScale (double *sx, double *sy) const
Undocumented public method.
void GetScaleAbs (double *sx, double *sy) const
Undocumented public method.
void GetTranslation (double *tx, double *ty) const
Undocumented public method.
double InverseDeterminant () const
Undocumented public method.
const BAffineTransform & Invert ()
Undocumented public method.
bool IsDilation (double epsilon=kDefaultEpsilon) const
Undocumented public method.
bool IsEqual (const BAffineTransform &other, double epsilon=kDefaultEpsilon) const
Undocumented public method.
virtual bool IsFixedSize () const
Undocumented public method.
bool IsIdentity (double epsilon=kDefaultEpsilon) const
Undocumented public method.
bool IsValid (double epsilon=kDefaultEpsilon) const
Undocumented public method.
const BAffineTransform & Multiply (const BAffineTransform &other)
Undocumented public method.
const BAffineTransform & MultiplyInverse (const BAffineTransform &other)
Undocumented public method.
bool operator!= (const BAffineTransform &other) const
Undocumented public method.
BAffineTransform operator* (const BAffineTransform &other) const
Undocumented public method.
const BAffineTransform & operator*= (const BAffineTransform &other)
Undocumented public method.
BAffineTransform operator/ (const BAffineTransform &other) const
Undocumented public method.
const BAffineTransform & operator/= (const BAffineTransform &other)
Undocumented public method.
BAffineTransform & operator= (const BAffineTransform &copyFrom)
Undocumented public method.
bool operator== (const BAffineTransform &other) const
Undocumented public method.
BAffineTransform operator~ () const
Undocumented public method.
const BAffineTransform & PreMultiply (const BAffineTransform &other)
Undocumented public method.
const BAffineTransform & PreMultiplyInverse (const BAffineTransform &other)
Undocumented public method.
const BAffineTransform & PreRotateBy (double angleRadians)
Undocumented public method.
const BAffineTransform & PreScaleBy (double x, double y)
Undocumented public method.
const BAffineTransform & PreTranslateBy (double x, double y)
Undocumented public method.
const BAffineTransform & Reset ()
Undocumented public method.
const BAffineTransform & RotateBy (const BPoint &center, double angle)
Undocumented public method.
const BAffineTransform & RotateBy (double angle)
Undocumented public method.
BAffineTransform RotateByCopy (const BPoint &center, double angle) const
Undocumented public method.
BAffineTransform RotateByCopy (double angle) const
Undocumented public method.
double Rotation () const
Undocumented public method.
double Scale () const
Undocumented public method.
const BAffineTransform & ScaleBy (const BPoint &center, const BPoint &scale)
Undocumented public method.
const BAffineTransform & ScaleBy (const BPoint &center, double scale)
Undocumented public method.
const BAffineTransform & ScaleBy (const BPoint &center, double x, double y)
Undocumented public method.
const BAffineTransform & ScaleBy (const BPoint &scale)
Undocumented public method.
const BAffineTransform & ScaleBy (double scale)
Undocumented public method.
const BAffineTransform & ScaleBy (double x, double y)
Undocumented public method.
BAffineTransform ScaleByCopy (const BPoint &center, const BPoint &scale) const
Undocumented public method.
BAffineTransform ScaleByCopy (const BPoint &center, double scale) const
Undocumented public method.
BAffineTransform ScaleByCopy (const BPoint &center, double x, double y) const
Undocumented public method.
BAffineTransform ScaleByCopy (const BPoint &scale) const
Undocumented public method.
BAffineTransform ScaleByCopy (double scale) const
Undocumented public method.
BAffineTransform ScaleByCopy (double x, double y) const
Undocumented public method.
const BAffineTransform & SetScale (double scale)
Undocumented public method.
const BAffineTransform & SetScale (double x, double y)
Undocumented public method.
const BAffineTransform & ShearBy (const BPoint &center, const BPoint &shear)
Undocumented public method.
const BAffineTransform & ShearBy (const BPoint &center, double x, double y)
Undocumented public method.
const BAffineTransform & ShearBy (const BPoint &shear)
Undocumented public method.
const BAffineTransform & ShearBy (double x, double y)
Undocumented public method.
BAffineTransform ShearByCopy (const BPoint &center, const BPoint &shear) const
Undocumented public method.
BAffineTransform ShearByCopy (const BPoint &center, double x, double y) const
Undocumented public method.
BAffineTransform ShearByCopy (const BPoint &shear) const
Undocumented public method.
BAffineTransform ShearByCopy (double x, double y) const
Undocumented public method.
const BAffineTransform & TranslateBy (const BPoint &delta)
Undocumented public method.
const BAffineTransform & TranslateBy (double x, double y)
Undocumented public method.
BAffineTransform TranslateByCopy (const BPoint &delta) const
Undocumented public method.
BAffineTransform TranslateByCopy (double x, double y) const
Undocumented public method.
virtual type_code TypeCode () const
Undocumented public method.
virtual status_t Unflatten (type_code code, const void *buffer, ssize_t size)
Undocumented public method.
Public Member Functions inherited from BFlattenable
virtual ~BFlattenable ()
Destructor. Does nothing.
virtual bool AllowsTypeCode (type_code code) const
Get whether or not the supplied type_code is supported.
Static Public Member Functions
static BAffineTransform AffineRotation (double angle)
Undocumented public method.
static BAffineTransform AffineScaling (double scale)
Undocumented public method.
static BAffineTransform AffineScaling (double x, double y)
Undocumented public method.
static BAffineTransform AffineShearing (double x, double y)
Undocumented public method.
static BAffineTransform AffineTranslation (double x, double y)
Undocumented public method.
Public Attributes
double shx
Undocumented public variable.
double shy
Undocumented public variable.
double sx
Undocumented public variable.
double sy
Undocumented public variable.
double tx
Undocumented public variable.
double ty
Undocumented public variable.
Static Public Attributes
static constexpr double kDefaultEpsilon = 1e-14
Undocumented public variable.
Detailed Description
Undocumented class.
Since
Haiku R1
Constructor & Destructor Documentation
BAffineTransform() [1/3]
BAffineTransform::BAffineTransform ()
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Referenced by operator*(), and operator/().
BAffineTransform() [2/3]
BAffineTransform::BAffineTransform (double sx, double shy, double shx, double sy, double tx, double ty)
Undocumented public method.
Parameters
sx Undocumented
shy Undocumented
shx Undocumented
sy Undocumented
tx Undocumented
ty Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
BAffineTransform() [3/3]
BAffineTransform::BAffineTransform (const BAffineTransform & copyFrom)
Undocumented public method.
Parameters
copyFrom Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
~BAffineTransform()
virtual BAffineTransform::~BAffineTransform () virtual
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Member Function Documentation
AffineRotation()
static BAffineTransform BAffineTransform::AffineRotation (double angle) static
Undocumented public method.
Parameters
angle Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
AffineScaling() [1/2]
static BAffineTransform BAffineTransform::AffineScaling (double scale) static
Undocumented public method.
Parameters
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
AffineScaling() [2/2]
static BAffineTransform BAffineTransform::AffineScaling (double x, double y) static
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
AffineShearing()
static BAffineTransform BAffineTransform::AffineShearing (double x, double y) static
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Referenced by ShearBy().
AffineTranslation()
static BAffineTransform BAffineTransform::AffineTranslation (double x, double y) static
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Apply() [1/4]
void BAffineTransform::Apply (BPoint * point) const
Undocumented public method.
Parameters
point Undocumented
Since
Haiku R1
Apply() [2/4]
void BAffineTransform::Apply (BPoint * points, uint32 count) const
Undocumented public method.
Parameters
points Undocumented
count Undocumented
Since
Haiku R1
Apply() [3/4]
BPoint BAffineTransform::Apply (const BPoint & point) const
Undocumented public method.
Parameters
point Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Apply() [4/4]
void BAffineTransform::Apply (double * x, double * y) const inline
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Since
Haiku R1
References shx, shy, sx, sy, tx, and ty.
ApplyInverse() [1/4]
void BAffineTransform::ApplyInverse (BPoint * point) const
Undocumented public method.
Parameters
point Undocumented
Since
Haiku R1
ApplyInverse() [2/4]
void BAffineTransform::ApplyInverse (BPoint * points, uint32 count) const
Undocumented public method.
Parameters
points Undocumented
count Undocumented
Since
Haiku R1
ApplyInverse() [3/4]
BPoint BAffineTransform::ApplyInverse (const BPoint & point) const
Undocumented public method.
Parameters
point Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ApplyInverse() [4/4]
void BAffineTransform::ApplyInverse (double * x, double * y) const inline
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Since
Haiku R1
References InverseDeterminant(), shx, shy, sx, sy, tx, and ty.
Determinant()
double BAffineTransform::Determinant () const inline
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, and sy.
Flatten()
virtual status_t BAffineTransform::Flatten (void * buffer, ssize_t size) const virtual
Undocumented public method.
Parameters
buffer Undocumented
size Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Implements BFlattenable.
FlattenedSize()
virtual ssize_t BAffineTransform::FlattenedSize () const virtual
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Implements BFlattenable.
FlipX()
const BAffineTransform & BAffineTransform::FlipX ()
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
FlipY()
const BAffineTransform & BAffineTransform::FlipY ()
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
GetAffineParameters()
bool BAffineTransform::GetAffineParameters (double * translationX, double * translationY, double * rotation, double * scaleX, double * scaleY, double * shearX, double * shearY) const
Undocumented public method.
Parameters
translationX Undocumented
translationY Undocumented
rotation Undocumented
scaleX Undocumented
scaleY Undocumented
shearX Undocumented
shearY Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
GetScale()
void BAffineTransform::GetScale (double * sx, double * sy) const
Undocumented public method.
Parameters
sx Undocumented
sy Undocumented
Since
Haiku R1
GetScaleAbs()
void BAffineTransform::GetScaleAbs (double * sx, double * sy) const
Undocumented public method.
Parameters
sx Undocumented
sy Undocumented
Since
Haiku R1
GetTranslation()
void BAffineTransform::GetTranslation (double * tx, double * ty) const
Undocumented public method.
Parameters
tx Undocumented
ty Undocumented
Since
Haiku R1
InverseDeterminant()
double BAffineTransform::InverseDeterminant () const inline
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, and sy.
Referenced by ApplyInverse().
Invert()
const BAffineTransform & BAffineTransform::Invert ()
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Referenced by MultiplyInverse(), operator~(), and PreMultiplyInverse().
IsDilation()
bool BAffineTransform::IsDilation (double epsilon = kDefaultEpsilon) const
Undocumented public method.
Parameters
epsilon Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
IsEqual()
bool BAffineTransform::IsEqual (const BAffineTransform & other, double epsilon = kDefaultEpsilon) const
Undocumented public method.
Parameters
other Undocumented
epsilon Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Referenced by operator!=(), and operator==().
IsFixedSize()
virtual bool BAffineTransform::IsFixedSize () const virtual
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Implements BFlattenable.
IsIdentity()
bool BAffineTransform::IsIdentity (double epsilon = kDefaultEpsilon) const
Undocumented public method.
Parameters
epsilon Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
IsValid()
bool BAffineTransform::IsValid (double epsilon = kDefaultEpsilon) const
Undocumented public method.
Parameters
epsilon Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Multiply()
const BAffineTransform & BAffineTransform::Multiply (const BAffineTransform & other) inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References PreMultiply().
Referenced by MultiplyInverse(), operator*(), operator*=(), and PreMultiplyInverse().
MultiplyInverse()
const BAffineTransform & BAffineTransform::MultiplyInverse (const BAffineTransform & other) inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References Invert(), and Multiply().
Referenced by operator/(), and operator/=().
operator!=()
bool BAffineTransform::operator!= (const BAffineTransform & other) const inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References IsEqual().
operator*()
BAffineTransform BAffineTransform::operator* (const BAffineTransform & other) const inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References BAffineTransform(), and Multiply().
operator*=()
const BAffineTransform & BAffineTransform::operator*= (const BAffineTransform & other) inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References Multiply().
operator/()
BAffineTransform BAffineTransform::operator/ (const BAffineTransform & other) const inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References BAffineTransform(), and MultiplyInverse().
operator/=()
const BAffineTransform & BAffineTransform::operator/= (const BAffineTransform & other) inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References MultiplyInverse().
operator=()
BAffineTransform & BAffineTransform::operator= (const BAffineTransform & copyFrom) inline
Undocumented public method.
Parameters
copyFrom Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, sy, tx, and ty.
operator==()
bool BAffineTransform::operator== (const BAffineTransform & other) const inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References IsEqual().
operator~()
BAffineTransform BAffineTransform::operator~ () const inline
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References Invert().
PreMultiply()
const BAffineTransform & BAffineTransform::PreMultiply (const BAffineTransform & other)
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Referenced by Multiply(), and ShearBy().
PreMultiplyInverse()
const BAffineTransform & BAffineTransform::PreMultiplyInverse (const BAffineTransform & other) inline
Undocumented public method.
Parameters
other Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References Invert(), and Multiply().
PreRotateBy()
const BAffineTransform & BAffineTransform::PreRotateBy (double angleRadians) inline
Undocumented public method.
Parameters
angleRadians Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, and sy.
PreScaleBy()
const BAffineTransform & BAffineTransform::PreScaleBy (double x, double y) inline
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, and sy.
PreTranslateBy()
const BAffineTransform & BAffineTransform::PreTranslateBy (double x, double y) inline
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, sy, tx, and ty.
Reset()
const BAffineTransform & BAffineTransform::Reset ()
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
RotateBy() [1/2]
const BAffineTransform & BAffineTransform::RotateBy (const BPoint & center, double angle)
Undocumented public method.
Parameters
center Undocumented
angle Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
RotateBy() [2/2]
const BAffineTransform & BAffineTransform::RotateBy (double angle) inline
Undocumented public method.
Parameters
angle Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, sy, tx, and ty.
RotateByCopy() [1/2]
BAffineTransform BAffineTransform::RotateByCopy (const BPoint & center, double angle) const
Undocumented public method.
Parameters
center Undocumented
angle Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
RotateByCopy() [2/2]
BAffineTransform BAffineTransform::RotateByCopy (double angle) const
Undocumented public method.
Parameters
angle Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Rotation()
double BAffineTransform::Rotation () const
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Scale()
double BAffineTransform::Scale () const
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleBy() [1/6]
const BAffineTransform & BAffineTransform::ScaleBy (const BPoint & center, const BPoint & scale)
Undocumented public method.
Parameters
center Undocumented
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleBy() [2/6]
const BAffineTransform & BAffineTransform::ScaleBy (const BPoint & center, double scale)
Undocumented public method.
Parameters
center Undocumented
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleBy() [3/6]
const BAffineTransform & BAffineTransform::ScaleBy (const BPoint & center, double x, double y)
Undocumented public method.
Parameters
center Undocumented
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleBy() [4/6]
const BAffineTransform & BAffineTransform::ScaleBy (const BPoint & scale)
Undocumented public method.
Parameters
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleBy() [5/6]
const BAffineTransform & BAffineTransform::ScaleBy (double scale) inline
Undocumented public method.
Parameters
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, sy, tx, and ty.
ScaleBy() [6/6]
const BAffineTransform & BAffineTransform::ScaleBy (double x, double y) inline
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References shx, shy, sx, sy, tx, and ty.
ScaleByCopy() [1/6]
BAffineTransform BAffineTransform::ScaleByCopy (const BPoint & center, const BPoint & scale) const
Undocumented public method.
Parameters
center Undocumented
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleByCopy() [2/6]
BAffineTransform BAffineTransform::ScaleByCopy (const BPoint & center, double scale) const
Undocumented public method.
Parameters
center Undocumented
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleByCopy() [3/6]
BAffineTransform BAffineTransform::ScaleByCopy (const BPoint & center, double x, double y) const
Undocumented public method.
Parameters
center Undocumented
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleByCopy() [4/6]
BAffineTransform BAffineTransform::ScaleByCopy (const BPoint & scale) const
Undocumented public method.
Parameters
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleByCopy() [5/6]
BAffineTransform BAffineTransform::ScaleByCopy (double scale) const
Undocumented public method.
Parameters
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ScaleByCopy() [6/6]
BAffineTransform BAffineTransform::ScaleByCopy (double x, double y) const
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
SetScale() [1/2]
const BAffineTransform & BAffineTransform::SetScale (double scale)
Undocumented public method.
Parameters
scale Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
SetScale() [2/2]
const BAffineTransform & BAffineTransform::SetScale (double x, double y)
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ShearBy() [1/4]
const BAffineTransform & BAffineTransform::ShearBy (const BPoint & center, const BPoint & shear)
Undocumented public method.
Parameters
center Undocumented
shear Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ShearBy() [2/4]
const BAffineTransform & BAffineTransform::ShearBy (const BPoint & center, double x, double y)
Undocumented public method.
Parameters
center Undocumented
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ShearBy() [3/4]
const BAffineTransform & BAffineTransform::ShearBy (const BPoint & shear)
Undocumented public method.
Parameters
shear Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ShearBy() [4/4]
const BAffineTransform & BAffineTransform::ShearBy (double x, double y) inline
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References AffineShearing(), and PreMultiply().
ShearByCopy() [1/4]
BAffineTransform BAffineTransform::ShearByCopy (const BPoint & center, const BPoint & shear) const
Undocumented public method.
Parameters
center Undocumented
shear Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ShearByCopy() [2/4]
BAffineTransform BAffineTransform::ShearByCopy (const BPoint & center, double x, double y) const
Undocumented public method.
Parameters
center Undocumented
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ShearByCopy() [3/4]
BAffineTransform BAffineTransform::ShearByCopy (const BPoint & shear) const
Undocumented public method.
Parameters
shear Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
ShearByCopy() [4/4]
BAffineTransform BAffineTransform::ShearByCopy (double x, double y) const
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
TranslateBy() [1/2]
const BAffineTransform & BAffineTransform::TranslateBy (const BPoint & delta)
Undocumented public method.
Parameters
delta Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
TranslateBy() [2/2]
const BAffineTransform & BAffineTransform::TranslateBy (double x, double y) inline
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
References tx, and ty.
TranslateByCopy() [1/2]
BAffineTransform BAffineTransform::TranslateByCopy (const BPoint & delta) const
Undocumented public method.
Parameters
delta Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
TranslateByCopy() [2/2]
BAffineTransform BAffineTransform::TranslateByCopy (double x, double y) const
Undocumented public method.
Parameters
x Undocumented
y Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
TypeCode()
virtual type_code BAffineTransform::TypeCode () const virtual
Undocumented public method.
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Implements BFlattenable.
Unflatten()
virtual status_t BAffineTransform::Unflatten (type_code code, const void * buffer, ssize_t size) virtual
Undocumented public method.
Parameters
code Undocumented
buffer Undocumented
size Undocumented
Returns
Undocumented
Return values
<value> Undocumented
Since
Haiku R1
Implements BFlattenable.
Member Data Documentation
kDefaultEpsilon
double BAffineTransform::kDefaultEpsilon = 1e-14 static constexpr
Undocumented public variable.
Since
Haiku R1
shx
double BAffineTransform::shx
Undocumented public variable.
Since
Haiku R1
Referenced by Apply(), ApplyInverse(), Determinant(), InverseDeterminant(), operator=(), PreRotateBy(), PreScaleBy(), PreTranslateBy(), RotateBy(), ScaleBy(), and ScaleBy().
shy
double BAffineTransform::shy
Undocumented public variable.
Since
Haiku R1
Referenced by Apply(), ApplyInverse(), Determinant(), InverseDeterminant(), operator=(), PreRotateBy(), PreScaleBy(), PreTranslateBy(), RotateBy(), ScaleBy(), and ScaleBy().
sx
double BAffineTransform::sx
Undocumented public variable.
Since
Haiku R1
Referenced by Apply(), ApplyInverse(), Determinant(), InverseDeterminant(), operator=(), PreRotateBy(), PreScaleBy(), PreTranslateBy(), RotateBy(), ScaleBy(), and ScaleBy().
sy
double BAffineTransform::sy
Undocumented public variable.
Since
Haiku R1
Referenced by Apply(), ApplyInverse(), Determinant(), InverseDeterminant(), operator=(), PreRotateBy(), PreScaleBy(), PreTranslateBy(), RotateBy(), ScaleBy(), and ScaleBy().
tx
double BAffineTransform::tx
Undocumented public variable.
Since
Haiku R1
Referenced by Apply(), ApplyInverse(), operator=(), PreTranslateBy(), RotateBy(), ScaleBy(), ScaleBy(), and TranslateBy().
ty
double BAffineTransform::ty
Undocumented public variable.
Since
Haiku R1
Referenced by Apply(), ApplyInverse(), operator=(), PreTranslateBy(), RotateBy(), ScaleBy(), ScaleBy(), and TranslateBy().