The Haiku Book: BObjectList< T, Owning > Class Template Reference
API Documentation
BObjectList< T, Owning > Class Template Reference
Support Kit | (libbe.so)
BObjectList is a wrapper around BList that adds type safety, optional object ownership, search, and insert operations.
Public Member Functions
virtual ~BObjectList ()
Deletes the list.
Operators
BObjectList & operator= (const BObjectList &list)
Creates a new BObjectList as a copy of another list by overloading the = operator.
Adding and Removing Items
bool AddItem (T *)
Append the item to the end of the list.
bool AddItem (T *, int32)
Add item at the specified index.
bool RemoveItem (T *, bool deleteIfOwning=true)
Remove item from the list.
T * RemoveItemAt (int32)
Remove the item at index from the list.
void MakeEmpty (bool deleteIfOwning=true)
Clear all the items from the list.
T * ItemAt (int32) const
Return a pointer to the item at the given index.
bool ReplaceItem (int32 index, T *)
Replace an item with another one.
Reordering Items
T * SwapWithItem (int32 index, T *newItem)
Swap the item with the item at index.
bool MoveItem (int32 from, int32 to)
Move the item at from to the position of to.
void SortItems (CompareFunction)
Sort the items with the use of a supplied comparison function.
void SortItems (CompareFunctionWithState, void *state)
Sort the items with the use of a supplied comparison function and addtional state.
void HSortItems (CompareFunction)
Sort the items with the use of a supplied comparison function.
Querying Items
T * FirstItem () const
Return a pointer to the first item in the list.
T * LastItem () const
Return a pointer to the last item in the list.
int32 IndexOf (const T *) const
Return the index of item.
bool HasItem (const T *) const
Return whether or not item is in the list.
bool IsEmpty () const
Return whether or not there are items in the list.
int32 CountItems () const
Returns the number of items in the list.
Iterating Over Items
T * EachElement (EachFunction, void *)
Perform an action on each item in the list.
const T * EachElement (ConstEachFunction, void *) const
Perform an action on each item in the list.
Finding Items
const T * FindIf (const UnaryPredicate< T > &) const
Find items that match predicate.
T * FindIf (const UnaryPredicate< T > &)
Find items that match predicate.
T * BinarySearch (const T &, CompareFunction) const
Search for key in the list of items using the supplied comparison function via a binary search algorithm.
T * BinarySearch (const T &, CompareFunctionWithState, void *state) const
Search for key in the list of items using the supplied comparison function via a binary search algorithm.
Detailed Description
template<class T, bool Owning>
class BObjectList< T, Owning >
BObjectList is a wrapper around BList that adds type safety, optional object ownership, search, and insert operations.
Since
Haiku R1
Constructor & Destructor Documentation
~BObjectList()
template<class T , bool Owning> BObjectList< T, Owning >::~BObjectList () virtual
Deletes the list.
If the list owns its items they are deleted too.
Since
Haiku R1
Member Function Documentation
AddItem() [1/2]
template<class T , bool O> bool BObjectList< T, O >::AddItem (T * item)
Append the item to the end of the list.
Parameters
item The item to append.
Returns
Whether or not the item was appended.
Return values
true The item was appended.
false item was not appended, since resizing the BObjectList failed.
Since
Haiku R1
References BList::AddItem().
AddItem() [2/2]
template<class T , bool O> bool BObjectList< T, O >::AddItem (T * item, int32 index)
Add item at the specified index.
Parameters
item The item to add.
index The place in the list to add the item.
Returns
Whether or not the item was added.
Return values
true The item was added.
false Item was not added. Either the index is negative or invalid, or resizing the BObjectList failed.
Since
Haiku R1
References BList::AddItem().
BinarySearch() [1/2]
template<class T , bool O> T * BObjectList< T, O >::BinarySearch (const T & key, CompareFunction func) const
Search for key in the list of items using the supplied comparison function via a binary search algorithm.
Parameters
key The key to search for.
func The comparison function to use.
Returns
A pointer to T.
Since
Haiku R1
BinarySearch() [2/2]
template<class T , bool O> T * BObjectList< T, O >::BinarySearch (const T & key, CompareFunctionWithState func, void * state) const
Search for key in the list of items using the supplied comparison function via a binary search algorithm.
Parameters
key The key to search for.
func The comparison function to use.
state Additional information used to search for the item.
Returns
A pointer to T.
Since
Haiku R1
CountItems()
template<class T , bool O> int32 BObjectList< T, O >::CountItems () const
Returns the number of items in the list.
Returns
The number of items in the list as an int32.
Since
Haiku R1
References BList::CountItems().
Referenced by BObjectList< T, Owning >::operator=().
EachElement() [1/2]
template<class T , bool O> const T * BObjectList< T, O >::EachElement (ConstEachFunction func, void * params) const
Perform an action on each item in the list.
Parameters
func A function that takes a void* argument and returns a boolean.
params parameters for func.
Returns
A pointer to the item.
Since
Haiku R1
EachElement() [2/2]
template<class T , bool O> T * BObjectList< T, O >::EachElement (EachFunction func, void * params)
Perform an action on each item in the list.
Parameters
func A function that takes a void* argument and returns a boolean.
params parameters for func.
Returns
A pointer to the item.
Since
Haiku R1
FindIf() [1/2]
template<class T , bool O> T * BObjectList< T, O >::FindIf (const UnaryPredicate< T > & predicate)
Find items that match predicate.
Returns
A pointer to T.
Since
Haiku R1
FindIf() [2/2]
template<class T , bool O> const T * BObjectList< T, O >::FindIf (const UnaryPredicate< T > & predicate) const
Find items that match predicate.
Returns
A const pointer to T.
Since
Haiku R1
FirstItem()
template<class T , bool O> T * BObjectList< T, O >::FirstItem () const
Return a pointer to the first item in the list.
Returns
A pointer to the first item or NULL if the list is empty.
See also
BObjectList<T>::LastItem() const
Since
Haiku R1
References BList::FirstItem().
HasItem()
template<class T , bool O> bool BObjectList< T, O >::HasItem (const T * item) const
Return whether or not item is in the list.
Returns
true if the item was in the list, false otherwise.
Since
Haiku R1
References BList::HasItem().
HSortItems()
template<class T , bool O> void BObjectList< T, O >::HSortItems (CompareFunction function)
Sort the items with the use of a supplied comparison function.
Parameters
function The function used to sort the items.
Since
Haiku R1
IndexOf()
template<class T , bool O> int32 BObjectList< T, O >::IndexOf (const T * item) const
Return the index of item.
Returns
The index of the item, or -1 when the item is not in the list.
Since
Haiku R1
References BList::IndexOf().
IsEmpty()
template<class T , bool O> bool BObjectList< T, O >::IsEmpty () const
Return whether or not there are items in the list.
Returns
true if the list was empty, false otherwise.
Since
Haiku R1
References BList::IsEmpty().
ItemAt()
template<class T , bool O> T * BObjectList< T, O >::ItemAt (int32 index) const inline
Return a pointer to the item at the given index.
Parameters
index The item to retrieve.
Returns
A pointer to the item in that position, or NULL if the index is out of bounds.
Since
Haiku R1
References BList::ItemAt().
Referenced by BObjectList< T, Owning >::operator=().
LastItem()
template<class T , bool O> T * BObjectList< T, O >::LastItem () const
Return a pointer to the last item in the list.
Returns
A pointer to the last item or NULL if the list is empty.
See also
BObjectList<T>::FirstItem() const
Since
Haiku R1
References BList::LastItem().
MakeEmpty()
template<class T , bool Owning> void BObjectList< T, Owning >::MakeEmpty (bool deleteIfOwning = true)
Clear all the items from the list.
Parameters
deleteIfOwning Also deletes items if owned.
Since
Haiku R1
References BList::MakeEmpty().
MoveItem()
template<class T , bool O> bool BObjectList< T, O >::MoveItem (int32 from, int32 to)
Move the item at from to the position of to.
Parameters
from The index to move the item from.
to The index to move the item to.
Returns
Whether or not the items were moved.
Return values
true The items were moved.
false The from or to index was invalid.
See also
BList::MoveItem()
Since
Haiku R1
operator=()
template<class T , bool Owning> BObjectList< T, Owning > & BObjectList< T, Owning >::operator= (const BObjectList< T, Owning > & list)
Creates a new BObjectList as a copy of another list by overloading the = operator.
Parameters
list The list to copy from.
Since
Haiku R1
References BObjectList< T, Owning >::CountItems(), and BObjectList< T, Owning >::ItemAt().
RemoveItem()
template<class T , bool Owning> bool BObjectList< T, Owning >::RemoveItem (T * item, bool deleteIfOwning = true)
Remove item from the list.
Parameters
item The item to be removed.
deleteIfOwning Also delete the item if owned.
Returns
Whether or not the item was removed.
Return values
true The item was found and removed.
false The item was not in this list and thus not removed.
Since
Haiku R1
References BList::RemoveItem().
RemoveItemAt()
template<class T , bool O> T * BObjectList< T, O >::RemoveItemAt (int32 index)
Remove the item at index from the list.
Parameters
index The index of the item to be removed.
Returns
The pointer to the item that was removed, or NULL if the index was invalid.
Since
Haiku R1
References BList::RemoveItem().
ReplaceItem()
template<class T , bool Owning> bool BObjectList< T, Owning >::ReplaceItem (int32 index, T * item)
Replace an item with another one.
Parameters
index The offset in the list where to put the item.
item The new item to put in the list.
Returns
Whether or not the item was replaced.
Return values
true The item was replaced.
false The index was invalid.
Since
Haiku R1
SortItems() [1/2]
template<class T , bool O> void BObjectList< T, O >::SortItems (CompareFunction function)
Sort the items with the use of a supplied comparison function.
Parameters
function The function used to sort the items.
Since
Haiku R1
SortItems() [2/2]
template<class T , bool O> void BObjectList< T, O >::SortItems (CompareFunctionWithState function, void * state)
Sort the items with the use of a supplied comparison function and addtional state.
Parameters
function The function used to sort the items.
state Additional information used to sort the items.
Since
Haiku R1
SwapWithItem()
template<class T , bool O> T * BObjectList< T, O >::SwapWithItem (int32 index, T * item)
Swap the item with the item at index.
Parameters
index The offset in the list where to put the item.
item The new item to put in the list.
Returns
A pointer to the item in that position, or NULL if the index is out of bounds.
Since
Haiku R1