The Haiku Book: BLayoutBuilder::Base< ParentBuilder > Class Template Reference
API Documentation
BLayoutBuilder::Base< ParentBuilder > Class Template Reference
Interface Kit » Layout API
Base for all other layout builders in the BLayoutBuilder namespace.
Inherited by BLayoutBuilder::Cards< ParentBuilder >, BLayoutBuilder::Grid< ParentBuilder >, BLayoutBuilder::Group< ParentBuilder >, and .
Public Member Functions
ParentBuilder & End ()
Returns this builder's parent.
void SetParent (ParentBuilder *parent)
Internal method for use by BLayoutBuilder::Base subclasses, this is essential to the builder stack semantics.
Detailed Description
template<typename ParentBuilder>
class BLayoutBuilder::Base< ParentBuilder >
Base for all other layout builders in the BLayoutBuilder namespace.
This class provides the stack-like semantics for its subclasses. The BLayoutBuilder::Group, BLayoutBuilder::Grid and BLayoutBuilder::Split all provide methods such as AddGrid() AddGroup() and AddSplit(), which make a new builder, place it on top of your builder stack and return it. Now you are operating on the new builder. When you call the End() method on the new builder, you are returned the one you had previously been using. At any point, you are calling methods on whatever builder currently resides on the top of the stack. Here's an example of how these classes work.
BLayoutBuilder::Group<>(B_HORIZONTAL)
At this point our stack just contains a single builder, it looks like this:
Group<>
.AddGrid()
Now there is a Grid builder on top of the stack, so it looks like this
Group<>::GridBuilder
Group<>
Notice that the Grid on top of the stack is not a plain Grid<>, but a nested type from the Group<> class. This is an essential part of the builder classes, as this is what allows you to pop builders off the stack and get the correct type in return.
.AddSplit()
Now our stack looks like this:
Group<>::GridBuilder::SplitBuilder
Group<>::GridBuilder
Group<>
This could continue ad. nauseam, but at some point, you may finish with a builder, and you might want to continue manipulating the builder below it on the stack. To do this, you simply call the End() method like so:
.End()
And now the stack is back to this:
Group<>::GridBuilder
Group<>
So you are again working with the grid builder. You can add more BLayoutItems or BViews, or even more builders. Here's how it will all look together.
BLayoutBuilder::Group<>(B_HORIZONTAL)
    // working with the Group builder
    .AddGrid()
        // working with the Group<>::GridBuilder
        .AddSplit()
            // working with the Group<>::GridBuilder::SplitBuilder
        .End()
        // back to the Group<>::GridBuilder
Note that the C++ language does not impose any sequence points in such method chains. This means the arguments to all calls may be evaluated in an unexpected order. For exemple, the following code may not result in adding the 3 views in rows 0, 1 and 2 in the target grid:
// Don't do this!
int row = 0;
BLayoutBuilder::Grid<>(target)
    .Add(viewA, row++)
    .Add(viewB, row++)
    .Add(viewC, row++);
Since
Haiku R1
Member Function Documentation
End()
template<typename ParentBuilder > ParentBuilder & BLayoutBuilder::Base< ParentBuilder >::End () inline
Returns this builder's parent.
Since
Haiku R1
SetParent()
template<typename ParentBuilder > void BLayoutBuilder::Base< ParentBuilder >::SetParent (ParentBuilder * parent) inline
Internal method for use by BLayoutBuilder::Base subclasses, this is essential to the builder stack semantics.
Since
Haiku R1
Referenced by BLayoutBuilder::Cards< ParentBuilder >::AddCards(), BLayoutBuilder::Cards< ParentBuilder >::AddCards(), BLayoutBuilder::Cards< ParentBuilder >::AddCards(), BLayoutBuilder::Grid< ParentBuilder >::AddCards(), BLayoutBuilder::Grid< ParentBuilder >::AddCards(), BLayoutBuilder::Grid< ParentBuilder >::AddCards(), BLayoutBuilder::Group< ParentBuilder >::AddCards(), BLayoutBuilder::Group< ParentBuilder >::AddCards(), BLayoutBuilder::Group< ParentBuilder >::AddCards(), BLayoutBuilder::Split< ParentBuilder >::AddCards(), BLayoutBuilder::Split< ParentBuilder >::AddCards(), BLayoutBuilder::Split< ParentBuilder >::AddCards(), BLayoutBuilder::Cards< ParentBuilder >::AddGrid(), BLayoutBuilder::Cards< ParentBuilder >::AddGrid(), BLayoutBuilder::Cards< ParentBuilder >::AddGrid(), BLayoutBuilder::Grid< ParentBuilder >::AddGrid(), BLayoutBuilder::Grid< ParentBuilder >::AddGrid(), BLayoutBuilder::Group< ParentBuilder >::AddGrid(), BLayoutBuilder::Group< ParentBuilder >::AddGrid(), BLayoutBuilder::Group< ParentBuilder >::AddGrid(), BLayoutBuilder::Split< ParentBuilder >::AddGrid(), BLayoutBuilder::Split< ParentBuilder >::AddGrid(), BLayoutBuilder::Split< ParentBuilder >::AddGrid(), BLayoutBuilder::Cards< ParentBuilder >::AddGroup(), BLayoutBuilder::Cards< ParentBuilder >::AddGroup(), BLayoutBuilder::Cards< ParentBuilder >::AddGroup(), BLayoutBuilder::Grid< ParentBuilder >::AddGroup(), BLayoutBuilder::Grid< ParentBuilder >::AddGroup(), BLayoutBuilder::Grid< ParentBuilder >::AddGroup(), BLayoutBuilder::Group< ParentBuilder >::AddGroup(), BLayoutBuilder::Group< ParentBuilder >::AddGroup(), BLayoutBuilder::Group< ParentBuilder >::AddGroup(), BLayoutBuilder::Split< ParentBuilder >::AddGroup(), BLayoutBuilder::Split< ParentBuilder >::AddGroup(), BLayoutBuilder::Split< ParentBuilder >::AddGroup(), BLayoutBuilder::Cards< ParentBuilder >::AddSplit(), BLayoutBuilder::Cards< ParentBuilder >::AddSplit(), BLayoutBuilder::Grid< ParentBuilder >::AddSplit(), BLayoutBuilder::Grid< ParentBuilder >::AddSplit(), BLayoutBuilder::Group< ParentBuilder >::AddSplit(), BLayoutBuilder::Group< ParentBuilder >::AddSplit(), and BLayoutBuilder::Split< ParentBuilder >::AddSplit().