The Haiku Book: BLayoutBuilder::Split< ParentBuilder > Class Template Reference
API Documentation
BLayoutBuilder::Split< ParentBuilder > Class Template Reference
Interface Kit » Layout API | (libbe.so)
BLayoutBuilder::Base subclass for building BSplitViews.
Inherits BLayoutBuilder::Base< ParentBuilder >.
Public Types
typedef Cards< ThisBuilder > CardBuilder
Shorthand for builders returned by this builder's AddCards() methods.
typedef Grid< ThisBuilder > GridBuilder
Shorthand for builders returned by this builder's AddGrid() methods.
typedef Group< ThisBuilder > GroupBuilder
Shorthand for builders returned by this builder's AddGroup() methods.
typedef Split< ThisBuilder > SplitBuilder
Shorthand for builders returned by this builder's AddSplit() methods.
typedef Split< ParentBuilder > ThisBuilder
Shorthand representing the type of this.
Public Member Functions
Constructors
Split (orientation orientation=B_HORIZONTAL, float spacing=B_USE_DEFAULT_SPACING)
Creates a builder for a new BSplitView.
Split (BSplitView *view)
Creates a builder for an existing BSplitView.
Accessors
BSplitView * View () const
Get a pointer to the BView this builder's layout is attached to.
ThisBuilder & GetView (BView **_view)
Get a pointer to the BView this builder's layout is attached to.
ThisBuilder & GetSplitView (BSplitView **_view)
Get a pointer to the SplitBView this builder is attached to.
operator BSplitView * ()
Cast this builder into the layout object it represents.
Adding BViews and BLayoutItems
ThisBuilder & Add (BView *view)
Add a view to the underlying BSplitView.
ThisBuilder & Add (BView *view, float weight)
Add a view with a weight to the underlying BSplitView.
ThisBuilder & Add (BLayoutItem *item)
Add a item to the underlying BSplitView.
ThisBuilder & Add (BLayoutItem *item, float weight)
Add an item with a weight to the underlying BSplitView.
Adding BLayouts and their BView Pairs
A set of methods that add a BLayout or BView subclass and return a BLayoutBuilder::Base subclass representing the newly added object. These methods push a new builder on top of the stack, you will not be using this builder again until you call End().
GroupBuilder AddGroup (orientation orientation, float spacing=B_USE_DEFAULT_SPACING, float weight=1.0f)
Shorthand for builders returned by this builder's AddGroup() methods. BLayoutBuilder::Group<ParentBuilder>::AddGroup(orientation orientation, float spacing, float weight)
GroupBuilder AddGroup (BGroupView *groupView, float weight=1.0f)
Shorthand for builders returned by this builder's AddGroup() methods. BLayoutBuilder::Group<ParentBuilder>::AddGroup(BGroupView* groupView, float weight)
GroupBuilder AddGroup (BGroupLayout *groupLayout, float weight=1.0f)
Shorthand for builders returned by this builder's AddGroup() methods. BLayoutBuilder::Group<ParentBuilder>::AddGroup(BGroupLayout* groupLayout, float weight)
GridBuilder AddGrid (float horizontal=B_USE_DEFAULT_SPACING, float vertical=B_USE_DEFAULT_SPACING, float weight=1.0f)
Shorthand for builders returned by this builder's AddGrid() methods. BLayoutBuilder::Group<ParentBuilder>::AddGrid(float horizontalSpacing, float verticalSpacing, float weight)
GridBuilder AddGrid (BGridView *gridView, float weight=1.0f)
Shorthand for builders returned by this builder's AddGrid() methods. BLayoutBuilder::Group<ParentBuilder>::AddGrid(BGridView* gridView, float weight)
GridBuilder AddGrid (BGridLayout *gridLayout, float weight=1.0f)
Shorthand for builders returned by this builder's AddGrid() methods. BLayoutBuilder::Group<ParentBuilder>::AddGrid(BGridLayout* gridLayout, float weight)
SplitBuilder AddSplit (orientation orientation, float spacing=B_USE_DEFAULT_SPACING, float weight=1.0f)
Shorthand for builders returned by this builder's AddSplit() methods. BLayoutBuilder::Group<ParentBuilder>::AddSplit(orientation orientation, float spacing, float weight)
SplitBuilder AddSplit (BSplitView *splitView, float weight=1.0f)
Shorthand for builders returned by this builder's AddSplit() methods. BLayoutBuilder::Group<ParentBuilder>::AddSplit(BSplitView* splitView, float weight)
CardBuilder AddCards (float weight=1.0f)
Shorthand for builders returned by this builder's AddCards() methods. BLayoutBuilder::Group<ParentBuilder>::AddCards(float weight)
CardBuilder AddCards (BCardLayout *cardLayout, float weight=1.0f)
Shorthand for builders returned by this builder's AddCards() methods. BLayoutBuilder::Group<ParentBuilder>::AddCards(BCardLayout* cardLayout, float weight)
CardBuilder AddCards (BCardView *cardView, float weight=1.0f)
Shorthand for builders returned by this builder's AddCards() methods. BLayoutBuilder::Group<ParentBuilder>::AddCards(BCardView* cardView, float weight)
Collapsability of elements
ThisBuilder & SetCollapsible (bool collapsible)
Set the whether all the layout items in this view are collapsible.
ThisBuilder & SetCollapsible (int32 index, bool collapsible)
Set whether the item at index is collapsible.
ThisBuilder & SetCollapsible (int32 first, int32 last, bool collapsible)
Set whether the items from first to last are collapsible.
Insets
ThisBuilder & SetInsets (float left, float top, float right, float bottom)
Set the insets between the bounds of the view and the inner elements.
ThisBuilder & SetInsets (float horizontal, float vertical)
Set the insets between the bounds of the view and the inner elements.
ThisBuilder & SetInsets (float insets)
Set the insets between the bounds of the view and the inner elements.
Public Member Functions inherited from BLayoutBuilder::Base< ParentBuilder >
ParentBuilder & End ()
Returns this builder's parent.
void SetParent (ParentBuilder *parent)
Internal method for use by BLayoutBuilder::Base subclasses, this is essential to the builder stack semantics.
Detailed Description
template<typename ParentBuilder>
class BLayoutBuilder::Split< ParentBuilder >
BLayoutBuilder::Base subclass for building BSplitViews.
Since
Haiku R1
A BSplitView consists of elements, for which in between there are dividers that the user can manipulate to alter the division of space between each of the element.s
For a detailed view on the properties, see the class description.
Member Typedef Documentation
CardBuilder
template<typename ParentBuilder > Cards<ThisBuilder> BLayoutBuilder::Split< ParentBuilder >::CardBuilder
Shorthand for builders returned by this builder's AddCards() methods.
Since
Haiku R1
GridBuilder
template<typename ParentBuilder > Grid<ThisBuilder> BLayoutBuilder::Split< ParentBuilder >::GridBuilder
Shorthand for builders returned by this builder's AddGrid() methods.
Since
Haiku R1
GroupBuilder
template<typename ParentBuilder > Group<ThisBuilder> BLayoutBuilder::Split< ParentBuilder >::GroupBuilder
Shorthand for builders returned by this builder's AddGroup() methods.
Since
Haiku R1
SplitBuilder
template<typename ParentBuilder > Split<ThisBuilder> BLayoutBuilder::Split< ParentBuilder >::SplitBuilder
Shorthand for builders returned by this builder's AddSplit() methods.
Since
Haiku R1
ThisBuilder
template<typename ParentBuilder > Split<ParentBuilder> BLayoutBuilder::Split< ParentBuilder >::ThisBuilder
Shorthand representing the type of this.
Since
Haiku R1
Constructor & Destructor Documentation
Split() [1/2]
template<typename ParentBuilder > BLayoutBuilder::Split< ParentBuilder >::Split (orientation orientation = B_HORIZONTAL, float spacing = B_USE_DEFAULT_SPACING) inline
Creates a builder for a new BSplitView.
Parameters
orientation The orientation for the new BSplitView.
spacing The spacing for the new BSplitView.
Since
Haiku R1
Split() [2/2]
template<typename ParentBuilder > BLayoutBuilder::Split< ParentBuilder >::Split (BSplitView * view) inline
Creates a builder for an existing BSplitView.
Parameters
view The existing view to operate on.
Since
Haiku R1
Member Function Documentation
Add() [1/4]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::Add (BLayoutItem * item) inline
Add a item to the underlying BSplitView.
The layout item will be added to the right or the bottom of the existing elements.
Parameters
item The BLayoutItem to be added. The underlying BSplitView will take ownership of the object.
See also
BSplitView::Add(BLayoutItem*)
Since
Haiku R1
Add() [2/4]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::Add (BLayoutItem * item, float weight) inline
Add an item with a weight to the underlying BSplitView.
The layout item will be added to the right or the bottom of the existing elements.
Parameters
item The BLayoutItem to be added. The underlying BSplitView will take ownership of the object.
weight The weight of the item.
See also
BSplitView::Add(BLayoutItem*, float)
Since
Haiku R1
Add() [3/4]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::Add (BView * view) inline
Add a view to the underlying BSplitView.
The view will be added to the right or the bottom of the existing elements.
Parameters
view The BView to be added. The underlying BSplitView will take ownership of the object.
See also
BSplitView::Add(BView*)
Since
Haiku R1
Add() [4/4]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::Add (BView * view, float weight) inline
Add a view with a weight to the underlying BSplitView.
The view will be added to the right or the bottom of the existing elements.
Parameters
view The BView to be added. The underlying BSplitView will take ownership of the object.
weight The weight of the view.
See also
BSplitView::Add(BView*, float)
Since
Haiku R1
AddCards() [1/3]
template<typename ParentBuilder > Split< ParentBuilder >::CardBuilder BLayoutBuilder::Split< ParentBuilder >::AddCards (BCardLayout * cardLayout, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddCards() methods. BLayoutBuilder::Group<ParentBuilder>::AddCards(BCardLayout* cardLayout, float weight)
Parameters
cardLayout The existing layout that will be added to the underlying BSplitView.
weight The weight of the BCardLayout in the BSplitView this builder represents.
Returns
A CardBuilder representing the cardLayout.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Cards< ParentBuilder >::View().
AddCards() [2/3]
template<typename ParentBuilder > Split< ParentBuilder >::CardBuilder BLayoutBuilder::Split< ParentBuilder >::AddCards (BCardView * cardView, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddCards() methods. BLayoutBuilder::Group<ParentBuilder>::AddCards(BCardView* cardView, float weight)
Parameters
cardView The existing view that will be added to the underlying BSplitView.
weight The weight of the BCardLayout in the BSplitView this builder represents.
Returns
A CardBuilder representing the layout of t he cardView.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Cards< ParentBuilder >::View().
AddCards() [3/3]
template<typename ParentBuilder > Split< ParentBuilder >::CardBuilder BLayoutBuilder::Split< ParentBuilder >::AddCards (float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddCards() methods. BLayoutBuilder::Group<ParentBuilder>::AddCards(float weight)
Parameters
weight The weight of the BCardLayout in the BSplitView this builder represents.
Returns
A CardBuilder representing the new BCardLayout.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Cards< ParentBuilder >::View().
AddGrid() [1/3]
template<typename ParentBuilder > Split< ParentBuilder >::GridBuilder BLayoutBuilder::Split< ParentBuilder >::AddGrid (BGridLayout * gridLayout, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddGrid() methods. BLayoutBuilder::Group<ParentBuilder>::AddGrid(BGridLayout* gridLayout, float weight)
Parameters
gridLayout The BGridLayout to be added and used to construct the returned GridBuilder.
weight The weight for gridLayout in the BSplitView this builder represents.
Returns
A GridBuilder representing the gridLayout.
Since
Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGrid() [2/3]
template<typename ParentBuilder > Split< ParentBuilder >::GridBuilder BLayoutBuilder::Split< ParentBuilder >::AddGrid (BGridView * gridView, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddGrid() methods. BLayoutBuilder::Group<ParentBuilder>::AddGrid(BGridView* gridView, float weight)
Parameters
gridView The BGridView to be added and used to construct the returned GridBuilder.
weight The weight for gridView in the BSplitView this builder represents.
Returns
A GridBuilder representing the layout of the gridView.
Since
Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGrid() [3/3]
template<typename ParentBuilder > Split< ParentBuilder >::GridBuilder BLayoutBuilder::Split< ParentBuilder >::AddGrid (float horizontalSpacing = B_USE_DEFAULT_SPACING, float verticalSpacing = B_USE_DEFAULT_SPACING, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddGrid() methods. BLayoutBuilder::Group<ParentBuilder>::AddGrid(float horizontalSpacing, float verticalSpacing, float weight)
Since
Haiku R1 BLayoutBuilder::Group<ParentBuilder>::AddGrid(float horizontalSpacing, float verticalSpacing, float weight)
Parameters
horizontalSpacing The horizontal spacing for the new BGridLayout.
verticalSpacing The vertical spacing for the new BGridLayout.
weight The weight for the new BGridLayout in the BSplitView this builder represents.
Returns
A GridBuilder representing the newly created BGridLayout.
Since
Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGroup() [1/3]
template<typename ParentBuilder > Split< ParentBuilder >::GroupBuilder BLayoutBuilder::Split< ParentBuilder >::AddGroup (BGroupLayout * groupLayout, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddGroup() methods. BLayoutBuilder::Group<ParentBuilder>::AddGroup(BGroupLayout* groupLayout, float weight)
Parameters
groupLayout The BGroupLayout to be added.
weight The weight for groupLayout in the BGroupLayout this builder represents.
Returns
A GroupBuilder representing the groupLayout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGroup() [2/3]
template<typename ParentBuilder > Split< ParentBuilder >::GroupBuilder BLayoutBuilder::Split< ParentBuilder >::AddGroup (BGroupView * groupView, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddGroup() methods. BLayoutBuilder::Group<ParentBuilder>::AddGroup(BGroupView* groupView, float weight)
Parameters
groupView The BGroupView to be added.
weight The weight for groupView in the BGroupLayout this builder represents.
Returns
A GroupBuilder representing the layout of the groupView.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGroup() [3/3]
template<typename ParentBuilder > Split< ParentBuilder >::GroupBuilder BLayoutBuilder::Split< ParentBuilder >::AddGroup (orientation orientation, float spacing = B_USE_DEFAULT_SPACING, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddGroup() methods. BLayoutBuilder::Group<ParentBuilder>::AddGroup(orientation orientation, float spacing, float weight)
Parameters
orientation The orientation to use for the new BGroupLayout.
spacing The spacing to use for the new BGroupLayout.
weight The weight for the new BGroupLayout in the BGroupLayout this builder represents.
Returns
A GroupBuilder representing the newly created BGroupLayout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddSplit() [1/2]
template<typename ParentBuilder > SplitBuilder BLayoutBuilder::Split< ParentBuilder >::AddSplit (BSplitView * splitView, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddSplit() methods. BLayoutBuilder::Group<ParentBuilder>::AddSplit(BSplitView* splitView, float weight)
Parameters
splitView The BSplitView to be added.
weight The weight of the BSplitView in the BSplitView this builder represents.
Returns
A SplitBuilder representing the splitView.
Since
Haiku R1
AddSplit() [2/2]
template<typename ParentBuilder > Split< ParentBuilder >::SplitBuilder BLayoutBuilder::Split< ParentBuilder >::AddSplit (orientation orientation, float spacing = B_USE_DEFAULT_SPACING, float weight = 1.0f) inline
Shorthand for builders returned by this builder's AddSplit() methods. BLayoutBuilder::Group<ParentBuilder>::AddSplit(orientation orientation, float spacing, float weight)
Parameters
orientation The orientation of the new BSplitView.
spacing The spacing of the new BSplitView.
weight The weight, in this BSplitView for the new BSplitView.
Returns
A SplitBuilder representing the new BSplitView.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Split< ParentBuilder >::View().
GetSplitView()
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::GetSplitView (BSplitView ** _view) inline
Get a pointer to the SplitBView this builder is attached to.
Parameters
[out] _view The BSplitView this builder' is attached to.
GetView()
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::GetView (BView ** _view) inline
Get a pointer to the BView this builder's layout is attached to.
Parameters
[out] _view The BView this builder's layout is attached to.
Since
Haiku R1
operator BSplitView *()
template<typename ParentBuilder > BLayoutBuilder::Split< ParentBuilder >::operator BSplitView * () inline
Cast this builder into the layout object it represents.
Since
Haiku R1
SetCollapsible() [1/3]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::SetCollapsible (bool collapsible) inline
Set the whether all the layout items in this view are collapsible.
Parameters
collapsible true if all items in this layout are collapsible, false if they are not.
Since
Haiku R1
See also
BSplitView::SetCollapsible(bool)
References BLayoutBuilder::Split< ParentBuilder >::SetCollapsible().
Referenced by BLayoutBuilder::Split< ParentBuilder >::SetCollapsible(), BLayoutBuilder::Split< ParentBuilder >::SetCollapsible(), and BLayoutBuilder::Split< ParentBuilder >::SetCollapsible().
SetCollapsible() [2/3]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::SetCollapsible (int32 first, int32 last, bool collapsible) inline
Set whether the items from first to last are collapsible.
Parameters
first The index of the first item that you want the setting to apply to (zero-based).
last The index of the last item that you want the setting to apply to (zero-based).
collapsible true if the user may collaps the item, false if they may not.
Since
Haiku R1
See also
BSplitView::SetCollapsible(int32, int32, bool)
References BLayoutBuilder::Split< ParentBuilder >::SetCollapsible().
SetCollapsible() [3/3]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::SetCollapsible (int32 index, bool collapsible) inline
Set whether the item at index is collapsible.
Parameters
index The index of the item (zero-based).
collapsible true if the user may collaps the item, false if they may not.
Since
Haiku R1
See also
BSplitView::SetCollapsible(int32, bool)
References BLayoutBuilder::Split< ParentBuilder >::SetCollapsible().
SetInsets() [1/3]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::SetInsets (float horizontal, float vertical) inline
Set the insets between the bounds of the view and the inner elements.
Parameters
horizontal The left and right inset.
vertical The top and bottom inset.
Since
Haiku R1
See also
BSplitView::SetInsets(float, float)
References BLayoutBuilder::Split< ParentBuilder >::SetInsets().
SetInsets() [2/3]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::SetInsets (float insets) inline
Set the insets between the bounds of the view and the inner elements.
Parameters
insets The value for the left, top, right and bottom inset.
Since
Haiku R1
See also
BSplitView::SetInsets(float)
References BLayoutBuilder::Split< ParentBuilder >::SetInsets().
SetInsets() [3/3]
template<typename ParentBuilder > Split< ParentBuilder >::ThisBuilder & BLayoutBuilder::Split< ParentBuilder >::SetInsets (float left, float top, float right, float bottom) inline
Set the insets between the bounds of the view and the inner elements.
Parameters
left The left inset.
top The top inset.
right The right inset.
bottom The bottom inset.
Since
Haiku R1
See also
BSplitView::SetInsets(float, float, float, float)
References BLayoutBuilder::Split< ParentBuilder >::SetInsets().
Referenced by BLayoutBuilder::Split< ParentBuilder >::SetInsets(), BLayoutBuilder::Split< ParentBuilder >::SetInsets(), and BLayoutBuilder::Split< ParentBuilder >::SetInsets().
View()
template<typename ParentBuilder > BSplitView * BLayoutBuilder::Split< ParentBuilder >::View () const inline
Get a pointer to the BView this builder's layout is attached to.
Since
Haiku R1
Referenced by BLayoutBuilder::Cards< ParentBuilder >::AddSplit(), BLayoutBuilder::Cards< ParentBuilder >::AddSplit(), BLayoutBuilder::Grid< ParentBuilder >::AddSplit(), BLayoutBuilder::Grid< ParentBuilder >::AddSplit(), BLayoutBuilder::Group< ParentBuilder >::AddSplit(), BLayoutBuilder::Group< ParentBuilder >::AddSplit(), and BLayoutBuilder::Split< ParentBuilder >::AddSplit().