The Haiku Book: BLayoutBuilder::Group< ParentBuilder > Class Template Reference
API Documentation
BLayoutBuilder::Group< ParentBuilder > Class Template Reference
Interface Kit » Layout API | (libbe.so)
BLayoutBuilder::Base subclass for building BGroupLayouts.
Inherits BLayoutBuilder::Base< ParentBuilder >.
Public Types
typedef Cards< ThisBuilder > CardBuilder
Shorthand for builders returned by this builder's AddCards() methods.
typedef Grid< ThisBuilder > GridBuilder
Shorthand for builders returned by this builder's AddGrid() methods.
typedef Group< ThisBuilder > GroupBuilder
Shorthand for builders returned by this builder's AddGroup() methods.
typedef Split< ThisBuilder > SplitBuilder
Shorthand for builders returned by this builder's AddSplit() methods.
typedef Group< ParentBuilder > ThisBuilder
Shorthand representing the type of this.
Public Member Functions
Constructors
Group (orientation orientation=B_HORIZONTAL, float spacing=B_USE_DEFAULT_SPACING)
Creates a new BGroupView and targets it.
Group (BWindow *window, orientation orientation=B_HORIZONTAL, float spacing=B_USE_DEFAULT_SPACING)
Creates a new BGroupLayout, and attaches it to a BWindow.
Group (BView *view, orientation orientation=B_HORIZONTAL, float spacing=B_USE_DEFAULT_SPACING)
Creates a builder targeting an existing view.
Group (BGroupLayout *layout)
Creates a builder targeting a BGroupLayout.
Group (BGroupView *view)
Creates a builder targeting a BGroupView.
Accessors
BGroupLayout * Layout () const
Get a pointer to the layout this builder represents.
BView * View () const
Get a pointer to the BView this builder's layout is attached to.
ThisBuilder & GetLayout (BGroupLayout **_layout)
Get the layout this builder represents.
ThisBuilder & GetView (BView **_view)
Get a pointer to the BView this builder's layout is attached to.
operator BGroupLayout * ()
Cast this builder into the layout object it represents.
Adding BViews and BLayoutItems
ThisBuilder & Add (BView *view)
Add a BView to the BGroupLayout this builder represents.
ThisBuilder & Add (BView *view, float weight)
Add BView to the BGroupLayout this builder represents.
ThisBuilder & Add (BLayoutItem *item)
Add a BLayoutItem to the BGroupLayout this builder represents.
ThisBuilder & Add (BLayoutItem *item, float weight)
Add a BLayoutItem the BGroupLayout this builder represents.
Adding BLayouts and their BView Pairs
A set of methods that add a BLayout or BView subclass and return a BLayoutBuilder::Base subclass representing the newly added object. These methods push a new builder on top of the stack, you will not be using this builder again until you call End().
GroupBuilder AddGroup (orientation orientation, float spacing=B_USE_DEFAULT_SPACING, float weight=1.0f)
Add a new viewless BGroupLayout as a child to the layout that this builder represents and return a GroupBuilder representing the new layout.
GroupBuilder AddGroup (BGroupView *groupView, float weight=1.0f)
Add an existing BGroupView as a child to the layout that this builder represents and return a GroupBuilder representing the layout of the added groupView.
GroupBuilder AddGroup (BGroupLayout *groupLayout, float weight=1.0f)
Add an existing BGroupLayout as a child to the layout that this builder represents and return a GroupBuilder to the added layout.
GridBuilder AddGrid (float horizontal=B_USE_DEFAULT_SPACING, float vertical=B_USE_DEFAULT_SPACING, float weight=1.0f)
Add a new viewless BGridLayout as a child to the layout that this builder represents and return a GridBuilder representing the new layout.
GridBuilder AddGrid (BGridLayout *gridLayout, float weight=1.0f)
Add an existing BGridLayout as a child to the layout that this builder represents and return a GridBuilder to the added layout.
GridBuilder AddGrid (BGridView *gridView, float weight=1.0f)
Add an existing BGridView as a child to the layout this builder represents and return a GridBuilder representing the layout of the added gridView.
SplitBuilder AddSplit (orientation orientation, float spacing=B_USE_DEFAULT_SPACING, float weight=1.0f)
Add a new BSplitView as a child to the layout that this builder represents and return a SplitBuilder representing the new BSplitView.
SplitBuilder AddSplit (BSplitView *splitView, float weight=1.0f)
Add an existing BSplitView as a child to the layout this builder represents and return a SplitBuilder representing the layout of the added splitView.
CardBuilder AddCards (float weight=1.0f)
Add a new viewless BCardLayout as a child to the layout that this builder represents and return a CardBuilder representing the new layout.
CardBuilder AddCards (BCardLayout *cardLayout, float weight=1.0f)
Add an existing BCardLayout as a child to the layout that this builder represents and return a CardBuilder representing the added layout.
CardBuilder AddCards (BCardView *cardView, float weight=1.0f)
Add an existing BCardView as a child to the layout that this builder represents and return a CardBuilder representing the layout of the added BCardView.
Adding BSpaceLayoutItems
Some convenience methods for adding special BSpaceLayoutItems.
ThisBuilder & AddGlue (float weight=1.0f)
Add a BSpaceLayoutItem created by BSpaceLayoutItem::CreateGlue() to the builder's layout.
ThisBuilder & AddStrut (float size)
Add a BSpaceLayoutItem created by BSpaceLayoutItem::CreateHorizontalStrut() or BSpaceLayoutItem::CreateVerticalStrut() to the BGroupLayout this builder represents.
Insets
ThisBuilder & SetInsets (float left, float top, float right, float bottom)
Set the insets for this layout.
ThisBuilder & SetInsets (float horizontal, float vertical)
Set the insets for this layout.
ThisBuilder & SetInsets (float insets)
Set the insets for this layout.
Explicit Sizes and Alignment
ThisBuilder & SetExplicitMinSize (BSize size)
Set the explicit minimum size of the underlying layout.
ThisBuilder & SetExplicitMaxSize (BSize size)
Set the explicit maximum size of the underlying layout.
ThisBuilder & SetExplicitPreferredSize (BSize size)
Set the explicit preferred size of the underlying layout.
ThisBuilder & SetExplicitAlignment (BAlignment alignment)
Set the explicit alignment of the underlying layout.
Public Member Functions inherited from BLayoutBuilder::Base< ParentBuilder >
ParentBuilder & End ()
Returns this builder's parent.
void SetParent (ParentBuilder *parent)
Internal method for use by BLayoutBuilder::Base subclasses, this is essential to the builder stack semantics.
Detailed Description
template<typename ParentBuilder>
class BLayoutBuilder::Group< ParentBuilder >
BLayoutBuilder::Base subclass for building BGroupLayouts.
Since
Haiku R1
Member Typedef Documentation
CardBuilder
template<typename ParentBuilder > Cards<ThisBuilder> BLayoutBuilder::Group< ParentBuilder >::CardBuilder
Shorthand for builders returned by this builder's AddCards() methods.
Since
Haiku R1
GridBuilder
template<typename ParentBuilder > Grid<ThisBuilder> BLayoutBuilder::Group< ParentBuilder >::GridBuilder
Shorthand for builders returned by this builder's AddGrid() methods.
Since
Haiku R1
GroupBuilder
template<typename ParentBuilder > Group<ThisBuilder> BLayoutBuilder::Group< ParentBuilder >::GroupBuilder
Shorthand for builders returned by this builder's AddGroup() methods.
Since
Haiku R1
SplitBuilder
template<typename ParentBuilder > Split<ThisBuilder> BLayoutBuilder::Group< ParentBuilder >::SplitBuilder
Shorthand for builders returned by this builder's AddSplit() methods.
Since
Haiku R1
ThisBuilder
template<typename ParentBuilder > Group<ParentBuilder> BLayoutBuilder::Group< ParentBuilder >::ThisBuilder
Shorthand representing the type of this.
Since
Haiku R1
Constructor & Destructor Documentation
Group() [1/5]
template<typename ParentBuilder > BLayoutBuilder::Group< ParentBuilder >::Group (orientation orientation = B_HORIZONTAL, float spacing = B_USE_DEFAULT_SPACING) inline
Creates a new BGroupView and targets it.
Methods called on this builder will be directed to the new BGroupView's BGroupLayout.
Parameters
orientation The orientation for the new BGroupView.
spacing The spacing for the new BGroupView.
Since
Haiku R1
Group() [2/5]
template<typename ParentBuilder > BLayoutBuilder::Group< ParentBuilder >::Group (BWindow * window, orientation orientation = B_HORIZONTAL, float spacing = B_USE_DEFAULT_SPACING) inline
Creates a new BGroupLayout, and attaches it to a BWindow.
Note
The top BView* in window has its ViewColor set to B_PANEL_BACKGROUND_COLOR.
Parameters
window The BWindow* to attach the newly created BGroupLayout to.
orientation The orientation for the new BGroupLayout.
spacing The spacing for the new BGroupLayout.
Since
Haiku R1
References BLayout::Owner(), and BWindow::SetLayout().
Group() [3/5]
template<typename ParentBuilder > BLayoutBuilder::Group< ParentBuilder >::Group (BView * view, orientation orientation = B_HORIZONTAL, float spacing = B_USE_DEFAULT_SPACING) inline
Creates a builder targeting an existing view.
Parameters
view The BView* to attach the newly created BGroupLayout to.
orientation The orientation for the new BGroupLayout.
spacing The spacing for the new BGroupLayout.
Since
Haiku R1
References BView::AdoptSystemColors(), BView::HasDefaultColors(), and BView::SetLayout().
Group() [4/5]
template<typename ParentBuilder > BLayoutBuilder::Group< ParentBuilder >::Group (BGroupLayout * layout) inline
Creates a builder targeting a BGroupLayout.
Methods called on this builder will be directed to layout.
Parameters
layout The BGroupLayout to target with this builder.
Since
Haiku R1
Group() [5/5]
template<typename ParentBuilder > BLayoutBuilder::Group< ParentBuilder >::Group (BGroupView * view) inline
Creates a builder targeting a BGroupView.
Methods called on this builder will be directed to view->GroupLayout().
Parameters
view The BGroupView this builder will target.
Since
Haiku R1
Member Function Documentation
Add() [1/4]
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::Add (BLayoutItem * item) inline
Add a BLayoutItem to the BGroupLayout this builder represents.
Parameters
item The BLayoutItem to be added.
See also
BGroupLayout::AddItem(BLayoutItem*)
Since
Haiku R1
Add() [2/4]
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::Add (BLayoutItem * item, float weight) inline
Add a BLayoutItem the BGroupLayout this builder represents.
Parameters
item The BLayoutItem to be added.
weight The weight to give item.
See also
BGroupLayout::AddItem(BLayoutItem* item, float weight)
Since
Haiku R1
Add() [3/4]
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::Add (BView * view) inline
Add a BView to the BGroupLayout this builder represents.
Parameters
view The BView to be added.
See also
BGroupLayout::AddView(BView*)
Since
Haiku R1
Add() [4/4]
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::Add (BView * view, float weight) inline
Add BView to the BGroupLayout this builder represents.
Parameters
view The BView to be added.
weight The weight to give view.
See also
BGroupLayout::AddView(BView* view, float weight)
Since
Haiku R1
AddCards() [1/3]
template<typename ParentBuilder > Group< ParentBuilder >::CardBuilder BLayoutBuilder::Group< ParentBuilder >::AddCards (BCardLayout * cardLayout, float weight = 1.0f) inline
Add an existing BCardLayout as a child to the layout that this builder represents and return a CardBuilder representing the added layout.
Parameters
cardLayout The existing layout to add to the current group layout.
weight The weight of this new layout within the current group layout.
Returns
A CardBuilder representing the cardLayout.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Cards< ParentBuilder >::View().
AddCards() [2/3]
template<typename ParentBuilder > Group< ParentBuilder >::CardBuilder BLayoutBuilder::Group< ParentBuilder >::AddCards (BCardView * cardView, float weight = 1.0f) inline
Add an existing BCardView as a child to the layout that this builder represents and return a CardBuilder representing the layout of the added BCardView.
Parameters
cardView The existing BCardView to add to the current group layout.
weight The weight of this new layout within the current group layout.
Returns
A CardBuilder representing the layout of the cardView.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Cards< ParentBuilder >::View().
AddCards() [3/3]
template<typename ParentBuilder > Group< ParentBuilder >::CardBuilder BLayoutBuilder::Group< ParentBuilder >::AddCards (float weight = 1.0f) inline
Add a new viewless BCardLayout as a child to the layout that this builder represents and return a CardBuilder representing the new layout.
Parameters
weight The weight of this new layout within the current group layout.
Returns
A CardBuilder representing the new BCardLayout.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Cards< ParentBuilder >::View().
AddGlue()
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::AddGlue (float weight = 1.0f) inline
Add a BSpaceLayoutItem created by BSpaceLayoutItem::CreateGlue() to the builder's layout.
Parameters
weight The weight of the BSpaceLayoutItem in the BGroupLayout this builder represents
Since
Haiku R1
References BSpaceLayoutItem::CreateGlue().
AddGrid() [1/3]
template<typename ParentBuilder > Group< ParentBuilder >::GridBuilder BLayoutBuilder::Group< ParentBuilder >::AddGrid (BGridLayout * gridLayout, float weight = 1.0f) inline
Add an existing BGridLayout as a child to the layout that this builder represents and return a GridBuilder to the added layout.
Parameters
gridLayout The BGridLayout to be added.
weight The weight for gridLayout in the BGroupLayout this builder represents.
Returns
A GridBuilder representing gridLayout.
Since
Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGrid() [2/3]
template<typename ParentBuilder > Group< ParentBuilder >::GridBuilder BLayoutBuilder::Group< ParentBuilder >::AddGrid (BGridView * gridView, float weight = 1.0f) inline
Add an existing BGridView as a child to the layout this builder represents and return a GridBuilder representing the layout of the added gridView.
Parameters
gridView The BGridView to be added.
weight The weight for gridView in this BGroupLayout.
Returns
A GridBuilder representing the layout of the gridView.
Since
Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGrid() [3/3]
template<typename ParentBuilder > Group< ParentBuilder >::GridBuilder BLayoutBuilder::Group< ParentBuilder >::AddGrid (float horizontalSpacing = B_USE_DEFAULT_SPACING, float verticalSpacing = B_USE_DEFAULT_SPACING, float weight = 1.0f) inline
Add a new viewless BGridLayout as a child to the layout that this builder represents and return a GridBuilder representing the new layout.
Parameters
horizontalSpacing The horizontal spacing for the new BGridLayout.
verticalSpacing The vertical spacing for the new BGridLayout.
weight The weight for the new BGroupLayout in the BGroupLayout this builder represents.
Returns
A GridBuilder representing the newly created BGridLayout.
Since
Haiku R1
References BLayoutBuilder::Grid< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGroup() [1/3]
template<typename ParentBuilder > Group< ParentBuilder >::GroupBuilder BLayoutBuilder::Group< ParentBuilder >::AddGroup (BGroupLayout * groupLayout, float weight = 1.0f) inline
Add an existing BGroupLayout as a child to the layout that this builder represents and return a GroupBuilder to the added layout.
Parameters
groupLayout The BGroupLayout to be added.
weight The weight for groupLayout in this group layout.
Returns
A GroupBuilder representing the groupLayout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGroup() [2/3]
template<typename ParentBuilder > Group< ParentBuilder >::GroupBuilder BLayoutBuilder::Group< ParentBuilder >::AddGroup (BGroupView * groupView, float weight = 1.0f) inline
Add an existing BGroupView as a child to the layout that this builder represents and return a GroupBuilder representing the layout of the added groupView.
Parameters
groupView The BGroupView to be added.
weight The weight for groupView in this group layout.
Returns
A GroupBuilder representing the layout of the groupView.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddGroup() [3/3]
template<typename ParentBuilder > Group< ParentBuilder >::GroupBuilder BLayoutBuilder::Group< ParentBuilder >::AddGroup (orientation orientation, float spacing = B_USE_DEFAULT_SPACING, float weight = 1.0f) inline
Add a new viewless BGroupLayout as a child to the layout that this builder represents and return a GroupBuilder representing the new layout.
Parameters
orientation The orientation to use for the new BGroupLayout.
spacing The spacing to use for the new BGroupLayout.
weight The weight for the new BGroupLayout in this group layout.
Returns
A GroupBuilder representing the newly created BGroupLayout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::Layout(), and BLayoutBuilder::Base< ParentBuilder >::SetParent().
AddSplit() [1/2]
template<typename ParentBuilder > Group< ParentBuilder >::SplitBuilder BLayoutBuilder::Group< ParentBuilder >::AddSplit (BSplitView * splitView, float weight = 1.0f) inline
Add an existing BSplitView as a child to the layout this builder represents and return a SplitBuilder representing the layout of the added splitView.
Parameters
splitView The BSplitView to be added.
weight The weight of the BSplitView in the BGroupLayout this builder represents.
Returns
A SplitBuilder representing the splitView.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Split< ParentBuilder >::View().
AddSplit() [2/2]
template<typename ParentBuilder > Group< ParentBuilder >::SplitBuilder BLayoutBuilder::Group< ParentBuilder >::AddSplit (orientation orientation, float spacing = B_USE_DEFAULT_SPACING, float weight = 1.0f) inline
Add a new BSplitView as a child to the layout that this builder represents and return a SplitBuilder representing the new BSplitView.
Parameters
orientation The orientation of the new BSplitView.
spacing The spacing of the new BSplitView.
weight The weight, in this BGroupLayout for the new BSplitView.
Returns
A SplitBuilder representing the new BSplitView.
Since
Haiku R1
References BLayoutBuilder::Base< ParentBuilder >::SetParent(), and BLayoutBuilder::Split< ParentBuilder >::View().
AddStrut()
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::AddStrut (float size) inline
Add a BSpaceLayoutItem created by BSpaceLayoutItem::CreateHorizontalStrut() or BSpaceLayoutItem::CreateVerticalStrut() to the BGroupLayout this builder represents.
Parameters
size The width or height of the strut to be created (depending on the orientation of the BGroupLayout this builder represents).
Since
Haiku R1
References B_HORIZONTAL, BSpaceLayoutItem::CreateHorizontalStrut(), and BSpaceLayoutItem::CreateVerticalStrut().
GetLayout()
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::GetLayout (BGroupLayout ** _layout) inline
Get the layout this builder represents.
Parameters
[out] _layout The layout this builder represents.
Since
Haiku R1
GetView()
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::GetView (BView ** _view) inline
Get a pointer to the BView this builder's layout is attached to.
Parameters
[out] _view The BView this builder's layout is attached to.
Since
Haiku R1
Layout()
template<typename ParentBuilder > BGroupLayout * BLayoutBuilder::Group< ParentBuilder >::Layout () const inline
Get a pointer to the layout this builder represents.
Since
Haiku R1
Referenced by BLayoutBuilder::Cards< ParentBuilder >::AddGroup(), BLayoutBuilder::Cards< ParentBuilder >::AddGroup(), BLayoutBuilder::Cards< ParentBuilder >::AddGroup(), BLayoutBuilder::Grid< ParentBuilder >::AddGroup(), BLayoutBuilder::Grid< ParentBuilder >::AddGroup(), BLayoutBuilder::Grid< ParentBuilder >::AddGroup(), BLayoutBuilder::Group< ParentBuilder >::AddGroup(), BLayoutBuilder::Group< ParentBuilder >::AddGroup(), BLayoutBuilder::Group< ParentBuilder >::AddGroup(), BLayoutBuilder::Split< ParentBuilder >::AddGroup(), BLayoutBuilder::Split< ParentBuilder >::AddGroup(), and BLayoutBuilder::Split< ParentBuilder >::AddGroup().
operator BGroupLayout *()
template<typename ParentBuilder > BLayoutBuilder::Group< ParentBuilder >::operator BGroupLayout * () inline
Cast this builder into the layout object it represents.
Since
Haiku R1
SetExplicitAlignment()
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::SetExplicitAlignment (BAlignment alignment) inline
Set the explicit alignment of the underlying layout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::SetExplicitAlignment().
Referenced by BLayoutBuilder::Group< ParentBuilder >::SetExplicitAlignment().
SetExplicitMaxSize()
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::SetExplicitMaxSize (BSize size) inline
Set the explicit maximum size of the underlying layout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::SetExplicitMaxSize().
Referenced by BLayoutBuilder::Group< ParentBuilder >::SetExplicitMaxSize().
SetExplicitMinSize()
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::SetExplicitMinSize (BSize size) inline
Set the explicit minimum size of the underlying layout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::SetExplicitMinSize().
Referenced by BLayoutBuilder::Group< ParentBuilder >::SetExplicitMinSize().
SetExplicitPreferredSize()
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::SetExplicitPreferredSize (BSize size) inline
Set the explicit preferred size of the underlying layout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::SetExplicitPreferredSize().
Referenced by BLayoutBuilder::Group< ParentBuilder >::SetExplicitPreferredSize().
SetInsets() [1/3]
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::SetInsets (float horizontal, float vertical) inline
Set the insets for this layout.
This is a convenience method to easily set similar insets.
Parameters
horizontal The insets to the left and right of the layout.
vertical The insets at the top and bottom of the layout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::SetInsets().
SetInsets() [2/3]
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::SetInsets (float insets) inline
Set the insets for this layout.
This is a convenience method that to easily set all the insets of the layout to the same value.
Parameters
insets The inset to be applied to left, top, right and bottom of this layout.
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::SetInsets().
SetInsets() [3/3]
template<typename ParentBuilder > Group< ParentBuilder >::ThisBuilder & BLayoutBuilder::Group< ParentBuilder >::SetInsets (float left, float top, float right, float bottom) inline
Set the insets for this layout.
Set the spacing around the edges of this layout. If you pass B_USE_DEFAULT_SPACING for a certain parameter, that parameter will be replaced with the value returned by BControlLook::DefaultItemSpacing().
Since
Haiku R1
References BLayoutBuilder::Group< ParentBuilder >::SetInsets().
Referenced by BLayoutBuilder::Group< ParentBuilder >::SetInsets(), BLayoutBuilder::Group< ParentBuilder >::SetInsets(), and BLayoutBuilder::Group< ParentBuilder >::SetInsets().
View()
template<typename ParentBuilder > BView * BLayoutBuilder::Group< ParentBuilder >::View () const inline
Get a pointer to the BView this builder's layout is attached to.
Since
Haiku R1